### ISSUE TITLE
System.NotSupportedException: Searching across multiple types is not supported. Thrown at Startup.

### ISSUE THREAD

**Issue by Kmanley1** [FirelyTeam/Vonk.Facade.Starter#55]
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NotSupportedException: Searching across multiple types is not supported.
   at Vonk.Facade.Relational.SearchRepository.Search(IArgumentCollection arguments, SearchOptions options)
   at Vonk.Core.Operations.Search.SearchService.Search(IArgumentCollection arguments, IVonkContext vonkContext)
   at Vonk.Core.Operations.Search.SearchService.Search(IVonkContext vonkContext)
   at Vonk.Core.Pluggability.VonkInteractionAsyncMiddleware`1.<>c__DisplayClass10_0.<<ExecuteService>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Vonk.Core.Support.LogHelpers.TrackDependencyAsync(TelemetryClient telemetryClient, String telemetryContext, Func`1 action)
   at Vonk.Core.Pluggability.VonkInteractionAsyncMiddleware`1.ExecuteService(HttpContext httpContext)
   at Vonk.Core.Pluggability.VonkInteractionAsyncMiddleware`1.InvokeAsync(HttpContext httpContext)
   at Vonk.Core.Pluggability.VonkInteractionAsyncMiddleware`1.InvokeAsync(HttpContext httpContext)
   at Vonk.Core.Pluggability.VonkInteractionMiddleware`1.InvokeAsync(HttpContext httpContext)
   at Vonk.Core.Pluggability.VonkInteractionMiddleware`1.InvokeAsync(HttpContext httpContext)
   at Vonk.Core.Context.Elements.SummaryMiddleware.Invoke(HttpContext context, ElementsHandler handler)
   at Vonk.Core.Context.Elements.ElementsMiddleware.Invoke(HttpContext context, ElementsHandler handler)
   at Vonk.Core.Pluggability.VonkInteractionMiddleware`1.InvokeAsync(HttpContext httpContext)
   at Vonk.Core.Pluggability.VonkInteractionMiddleware`1.InvokeAsync(HttpContext httpContext)
   at Vonk.Core.Infra.ResponseCache.CapabilityCacheMiddleware.Invoke(HttpContext context, CapabilityCache cache, ISerializationService serializationService)
   at Vonk.Core.Pluggability.VonkInteractionMiddleware`1.InvokeAsync(HttpContext httpContext)
   at Vonk.Core.Pluggability.VonkInteractionMiddleware`1.InvokeAsync(HttpContext httpContext)
   at Vonk.Core.Context.Http.VonkExceptionMiddleware.Invoke(HttpContext context)
   at Vonk.Core.Context.Http.VonkToHttpMiddleware.Invoke(HttpContext context, IFormatter formatter, PreferService preferService, IVonkOutcomeAdapter vonkOutcomeAdapter)
   at Vonk.Core.Context.Http.HttpToVonkMiddleware.Invoke(HttpContext context, IParsingService parser, ContentNegotiationService formatInterpreter)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

**Comment by vadi2** [comment]
Prefix the type you want to search on, for example instead of `[base]/Observation?reference=http://example.org/fhir/Patient/123` do `[base]/Observation?reference=Patient:http://example.org/fhir/Patient/123`

**Comment by Kmanley1** [comment]
Hello @vadi2 - thank you for your comment.  I apologize for my lack of understanding, I am just starting to work with FHIR and VONK.  The stack trace is from starting VONK not when searching.  Is there a configuration change needed using your suggestion or am I misunderstanding your comment.  Thank you.
